/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blarb (https://sketchfab.com/Blarb)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/camping-tent-3f624d58d582430595179bdf9a156be3
title: Camping tent
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/camping.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.tent001_Tent_0.geometry} material={materials.Tent} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/camping.gltf')
