/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BEAGAMER (https://sketchfab.com/BEAGAMER)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/pagani-huayra-bc-metallic-beryllium-orange-f3a4774883284e748b9081d2b2c60ed5
title: Pagani Huayra-BC | Metallic Beryllium Orange |
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/car.gltf");
  const wheel1 = useRef();
  useFrame(state => {
    // wheel1.current.rotation.y += 0.01;
    // wheel1.current.rotation.x += 0.01;
    // wheel1.current.rotation.z += 0.01;
    // group.current.rotation.x += 0.01;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.CSR2_Badge}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.CSR2_Base}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_9.geometry}
              material={nodes.Object_9.material}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={nodes.Object_10.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_12.geometry}
              material={nodes.Object_12.material}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={nodes.Object_13.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_15.geometry}
              material={nodes.Object_15.material}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={nodes.Object_16.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_18.geometry}
              material={nodes.Object_18.material}
            />
            <mesh
              geometry={nodes.Object_19.geometry}
              material={nodes.Object_19.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_21.geometry}
              material={materials.CSR2_Carbon1}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_23.geometry}
              material={materials.CSR2_Carbon1M}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_25.geometry}
              material={materials.CSR2_Carbon2M}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_27.geometry}
              material={nodes.Object_27.material}
            />
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials.Side_Mirror}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials.CSR2_Engine}
            />
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials.CSR2_EngineA}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials.GlassClear}
            />
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials.Window}
            />
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials.GlassRed}
            />
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials.CSR2_RedGlass_Light}
            />
            <mesh
              geometry={nodes.Object_37.geometry}
              material={materials.Glass_Back_Tail_light}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials.CSR2_Grille1}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_41.geometry}
              material={nodes.Object_41.material}
            />
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials.CSR2_InteriorA_Zone1}
            />
            <mesh
              geometry={nodes.Object_43.geometry}
              material={materials.CSR2_Interior_Zone1}
            />
            <mesh
              geometry={nodes.Object_44.geometry}
              material={nodes.Object_44.material}
            />
            <mesh
              geometry={nodes.Object_45.geometry}
              material={materials.CSR2_Interior_Zone2}
            />
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials.CSR2_InteriorA_Zone2}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_48.geometry}
              material={nodes.Object_48.material}
            />
            <mesh
              geometry={nodes.Object_49.geometry}
              material={nodes.Object_49.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_51.geometry}
              material={materials.CSR2_InteriorTilling}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials.CSR2_Light}
            />
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials.CSR2_Emissive}
            />
            <mesh
              geometry={nodes.Object_55.geometry}
              material={materials.CSR2_Emissive_Redlight_front}
            />
            <mesh
              geometry={nodes.Object_56.geometry}
              material={materials.CSR2_Back_RedLight}
            />
            <mesh
              geometry={nodes.Object_57.geometry}
              material={materials.CSR2_BACK_SMALL_EMISSIVE_LIGHT}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_59.geometry}
              material={materials.CSR2_CarPaint}
            />
            <mesh
              geometry={nodes.Object_60.geometry}
              material={materials.CSR2_OEM_Pagani_BiancoBluStripes_1}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_62.geometry}
              material={nodes.Object_62.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_64.geometry}
              material={nodes.Object_64.material}
            />
            <mesh
              geometry={nodes.Object_65.geometry}
              material={nodes.Object_65.material}
            />
            <mesh
              geometry={nodes.Object_66.geometry}
              material={nodes.Object_66.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_68.geometry}
              material={nodes.Object_68.material}
            />
            <mesh
              geometry={nodes.Object_69.geometry}
              material={nodes.Object_69.material}
            />
            <mesh
              geometry={nodes.Object_70.geometry}
              material={nodes.Object_70.material}
            />
          </group>
          {/* banh xe */}
          {/* <group ref={wheel1}> */}
          <group
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.11}
            // position={[0, 1.5, 0.45]}
          >
            <mesh
              geometry={nodes.Object_72.geometry}
              material={nodes.Object_72.material}
            />
            <mesh
              geometry={nodes.Object_73.geometry}
              material={nodes.Object_73.material}
            />
            <mesh
              geometry={nodes.Object_74.geometry}
              material={nodes.Object_74.material}
            />
          </group>
          {/* </group> */}

          <group rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
            <mesh
              geometry={nodes.Object_76.geometry}
              material={nodes.Object_76.material}
            />
            <mesh
              geometry={nodes.Object_77.geometry}
              material={nodes.Object_77.material}
            />
            <mesh
              geometry={nodes.Object_78.geometry}
              material={nodes.Object_78.material}
            />
          </group>
          <group position={[0, 1.77, 0]} scale={[15.89, 1.27, 15.89]}>
            <mesh
              geometry={nodes.Object_80.geometry}
              material={materials.Material}
            />
          </group>
          <group position={[0, 4.82, 0]} scale={[6.17, 0.61, 6.17]}>
            <mesh
              geometry={nodes.Object_82.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <group scale={22.19}>
            <mesh
              geometry={nodes.Object_84.geometry}
              material={materials["Material.047"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/car.gltf");
