/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Steven Grey (https://sketchfab.com/Steven007)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/ferrari-458-italia-89d34b49b6944859ac93cab60d822dec
title: Ferrari 458 Italia
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/ferrari458.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[80.82, 34.01, -149.96]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[114.49, 114.49, 114.49]}>
            <mesh
              geometry={nodes.object024_Material009_0.geometry}
              material={nodes.object024_Material009_0.material}
            />
          </group>
          <group position={[0, 102.57, -116.89]}>
            <mesh
              geometry={nodes.object020_Material011_0.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group position={[0, 78.69, 41.7]}>
            <mesh
              geometry={nodes.object023__121013SSPC_mirrors_0.geometry}
              material={materials["121013SSPC_mirrors"]}
            />
          </group>
          <group position={[0, 64.66, 19.62]}>
            <mesh
              geometry={nodes.object022_Material007_0.geometry}
              material={materials["Material.007"]}
            />
          </group>
          <group position={[0, 64.31, 165.41]}>
            <mesh
              geometry={nodes.object021_Material010_0.geometry}
              material={materials["Material.010"]}
            />
          </group>
          <group position={[0, 93.24, 20.11]}>
            <mesh
              geometry={nodes.object019_Material013_0.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <group position={[0, 59.81, 174.07]}>
            <mesh
              geometry={nodes.object018_Material006_0.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group position={[0, 80.82, -209.62]}>
            <mesh
              geometry={nodes.object017_Material001_0.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <group position={[0, 61.33, -199.61]}>
            <mesh
              geometry={nodes.object016_Material003_0.geometry}
              material={materials["Material.003"]}
            />
          </group>
          <group position={[0, 80.51, -204.85]}>
            <mesh
              geometry={nodes.object015_Material004_0.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group position={[0, 92.61, -27.87]}>
            <mesh
              geometry={nodes.object014_Material002_0.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group position={[0.05, 78.58, -140.27]}>
            <mesh
              geometry={nodes.object013_Material015_0.geometry}
              material={materials["Material.015"]}
            />
          </group>
          <group position={[0.03, 78.21, -125.08]}>
            <mesh
              geometry={nodes.object012_Material017_0.geometry}
              material={materials["Material.017"]}
            />
          </group>
          <group position={[-0.31, 78.35, -130.78]}>
            <mesh
              geometry={nodes.object011_Material018_0.geometry}
              material={materials["Material.018"]}
            />
          </group>
          <group position={[-0.01, 79.08, -170.63]}>
            <mesh
              geometry={nodes.object010_Material019_0.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group position={[0.12, 78.36, -95.28]}>
            <mesh
              geometry={nodes.object009_Material016_0.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group position={[0, 76.14, -130.72]}>
            <mesh
              geometry={nodes.object008_eng_0.geometry}
              material={materials.material}
            />
          </group>
          <group position={[0, 59.76, -0.89]}>
            <mesh
              geometry={nodes.object007_Material012_0.geometry}
              material={materials["Material.012"]}
            />
          </group>
          <group position={[0, 63.46, -4.39]}>
            <mesh
              geometry={nodes.object006_mesh_0.geometry}
              material={materials.mesh}
            />
          </group>
          <group position={[0, 62.25, -143.12]}>
            <mesh
              geometry={nodes.object005_carbon_0.geometry}
              material={materials.carbon}
            />
          </group>
          <group position={[0, 53.98, 184.59]}>
            <mesh
              geometry={nodes.object004_xenon_0.geometry}
              material={materials.xenon}
            />
          </group>
          <group position={[0, 59.81, 174.07]}>
            <mesh
              geometry={nodes.object003_Material008_0.geometry}
              material={materials["Material.008"]}
            />
          </group>
          <group position={[0, 64.32, 162.1]}>
            <mesh
              geometry={nodes.object002_emit_0.geometry}
              material={materials.emit}
            />
          </group>
          <group position={[0, 63.69, 0.48]}>
            <mesh
              geometry={nodes.object000_Material005_0.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0, 34.17, -223.55]}>
            <mesh
              geometry={nodes.object001_Material014_0.geometry}
              material={materials["Material.014"]}
            />
          </group>
          <group
            position={[-80.82, 34.01, -149.96]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={114.49}>
            <mesh
              geometry={nodes.object025_Material009_0.geometry}
              material={nodes.object025_Material009_0.material}
            />
          </group>
          <group
            position={[81.23, 27.38, 115.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[112.15, 112.15, 112.15]}>
            <mesh
              geometry={nodes.object027_Material009_0.geometry}
              material={nodes.object027_Material009_0.material}
            />
          </group>
          <group
            position={[-81.23, 27.38, 115.67]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={112.15}>
            <mesh
              geometry={nodes.object026_Material009_0.geometry}
              material={nodes.object026_Material009_0.material}
            />
          </group>
          <group
            position={[-81.23, 27.38, 115.67]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={112.15}>
            <mesh
              geometry={nodes.object028_Material022_0.geometry}
              material={nodes.object028_Material022_0.material}
            />
          </group>
          <group
            position={[-81.23, 27.38, 115.67]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={112.15}>
            <mesh
              geometry={nodes.object029_Material021_0.geometry}
              material={nodes.object029_Material021_0.material}
            />
          </group>
          <group
            position={[-81.23, 27.38, 115.67]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={[112.15, 112.15, 112.15]}>
            <mesh
              geometry={nodes.object030_Material020_0.geometry}
              material={nodes.object030_Material020_0.material}
            />
          </group>
          <group
            position={[-80.82, 34.01, -149.96]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={114.49}>
            <mesh
              geometry={nodes.object031_Material022_0.geometry}
              material={nodes.object031_Material022_0.material}
            />
          </group>
          <group
            position={[-80.82, 34.01, -149.96]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={114.49}>
            <mesh
              geometry={nodes.object032_Material021_0.geometry}
              material={nodes.object032_Material021_0.material}
            />
          </group>
          <group
            position={[-80.82, 34.01, -149.96]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={114.49}>
            <mesh
              geometry={nodes.object033_Material020_0.geometry}
              material={nodes.object033_Material020_0.material}
            />
          </group>
          <group
            position={[80.82, 34.01, -149.96]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[114.49, 114.49, 114.49]}>
            <mesh
              geometry={nodes.object034_Material022_0.geometry}
              material={nodes.object034_Material022_0.material}
            />
          </group>
          <group
            position={[80.82, 34.01, -149.96]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[114.49, 114.49, 114.49]}>
            <mesh
              geometry={nodes.object035_Material021_0.geometry}
              material={nodes.object035_Material021_0.material}
            />
          </group>
          <group
            position={[80.82, 34.01, -149.96]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[114.49, 114.49, 114.49]}>
            <mesh
              geometry={nodes.object036_Material020_0.geometry}
              material={nodes.object036_Material020_0.material}
            />
          </group>
          <group
            position={[81.23, 27.38, 115.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[112.15, 112.15, 112.15]}>
            <mesh
              geometry={nodes.object037_Material022_0.geometry}
              material={nodes.object037_Material022_0.material}
            />
          </group>
          <group
            position={[81.23, 27.38, 115.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[112.15, 112.15, 112.15]}>
            <mesh
              geometry={nodes.object038_Material021_0.geometry}
              material={nodes.object038_Material021_0.material}
            />
          </group>
          <group
            position={[81.23, 27.38, 115.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[112.15, 112.15, 112.15]}>
            <mesh
              geometry={nodes.object039_Material020_0.geometry}
              material={nodes.object039_Material020_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ferrari458.gltf");
