/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC PERFORMANCE (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-lamborghini-wheel-sdc-0102d9b0929242f6af72009ef465ff68
title: (FREE) Lamborghini Wheel - SDC
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ isStopRun = false, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/wheel.gltf");
  const wheel = useRef();
  useFrame(state => {
    !isStopRun ? (wheel.current.rotation.y += 0.5) : null;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2 - 1.5, 0, 0]} ref={wheel}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 0, -0.08]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.52, 0.62, 1.52]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={nodes.Object_4.material}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={nodes.Object_5.material}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group
            position={[0, 0, -1.16]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[4.74, 4.74, 4.74]}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.Matte__FF070707__spec}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials["plaquette_de_frein.002"]}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials["visse.002"]}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.Chrome_Text_Logo}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.CRBN_JANTE}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials["Material.027"]}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials["Material.012"]}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials["Material.030"]}
            />
          </group>
          <group position={[0, 3.67, 2.25]} scale={0.01}>
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.MetalDark}
            />
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials.MetalGoldenLogo}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/wheel.gltf");
